export const SMART_IQ_CLICKED = "SMART_IQ_CLICKED";
export const SLEEP_IQ_CLICKED = "SLEEP_IQ_CLICKED";
export const WEAR_LINQ_CLICKED = "WEAR_LINQ_CLICKED";
export const TEMP_IQ_CLICKED = "TEMP_IQ_CLICKED";
export const METRICS_UPDATED_FROM_FIRESTORE = "METRICS_UPDATED_FROM_FIRESTORE";
