export { default as About } from './About/About';
export { default as Application } from './Application/Application';
export { default as Brands } from './Brands/Brands';
export { default as Contact } from './Contact/Contact';
export { default as Dsm } from './Dsm/Dsm';
export { default as Features } from './Features/Features';
export { default as Footer } from './Footer/Footer';
export { default as Hero } from './Hero/Hero';
export { default as Team } from './Team/Team';
export { default as Team1} from './Team1/Team1';
export { default as Proof} from './Proof/Proof';